/*
 * Copyright (C) 2019 highstreet technologies GmbH Intellectual Property.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
package org.onap.ccsdk.features.sdnr.wt.odlclient.test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import java.io.IOException;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.stream.XMLStreamException;
import javax.xml.transform.TransformerException;
import org.custommonkey.xmlunit.XMLUnit;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.onap.ccsdk.features.sdnr.wt.odlclient.data.OdlObjectMapper;
import org.onap.ccsdk.features.sdnr.wt.odlclient.data.OdlObjectMapperXml;
import org.onap.ccsdk.features.sdnr.wt.odlclient.data.OdlRpcObjectMapperXml;
import org.onap.ccsdk.features.sdnr.wt.odlclient.data.OdlRpcObjectMapperXml2;
import org.opendaylight.yang.gen.v1.http.org.openroadm.device.rev181019.LedControlInputBuilder;
import org.opendaylight.yang.gen.v1.http.org.openroadm.device.rev181019.led.control.input.equipment.entity.ShelfBuilder;
import org.opendaylight.yang.gen.v1.http.org.openroadm.device.rev181019.org.openroadm.device.container.org.openroadm.device.Info;
import org.opendaylight.yang.gen.v1.urn.opendaylight.netconf.node.topology.rev150114.NetconfNode;
import org.opendaylight.yangtools.yang.model.api.SchemaContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.xml.sax.SAXException;

public class TestMapper {

    private static final Logger LOG = LoggerFactory.getLogger(TestMapper.class);

    private static final String INFOSTRING = " {\n" + "    \"org-openroadm-device:info\": {\n"
            + "        \"current-datetime\": \"2017-10-22T15:23:43Z\",\n" + "        \"vendor\": \"vendorA\",\n"
            + "        \"model\": \"model2\",\n" + "        \"softwareVersion\": \"swversion1234\",\n"
            + "        \"max-degrees\": 2,\n" + "        \"current-ipAddress\": \"127.0.0.11\",\n"
            + "        \"node-id\": \"ROADM-B1\",\n" + "        \"current-defaultGateway\": \"127.0.0.20\",\n"
            + "        \"clli\": \"NodeB\",\n" + "        \"prefix-length\": 28,\n"
            + "        \"current-prefix-length\": 28,\n" + "        \"macAddress\": \"00:01:02:03:04:05\",\n"
            + "        \"source\": \"static\",\n" + "        \"openroadm-version\": \"2.2.1\",\n"
            + "        \"geoLocation\": {\n" + "            \"latitude\": 1.0000,\n"
            + "            \"longitude\": 2.0000\n" + "        },\n"
            + "        \"max-num-bin-24hour-historical-pm\": 7,\n" + "        \"serial-id\": \"0002\",\n"
            + "        \"max-srgs\": 3,\n" + "        \"max-num-bin-15min-historical-pm\": 32,\n"
            + "        \"template\": \"template_1\",\n" + "        \"node-type\": \"rdm\",\n"
            + "        \"node-number\": 3,\n" + "        \"ipAddress\": \"127.0.0.11\",\n"
            + "        \"defaultGateway\": \"127.0.0.20\"\n" + "    }\n" + "}";
    private static final String INFOSTRING_XML = "<info xmlns=\"http://org/openroadm/device\">\n"
            + "    <current-datetime>2017-10-22T15:23:43Z</current-datetime>\n" + "    <vendor>vendorA</vendor>\n"
            + "    <model>model2</model>\n" + "    <softwareVersion>swversion1234</softwareVersion>\n"
            + "    <max-degrees>2</max-degrees>\n" + "    <current-ipAddress>127.0.0.11</current-ipAddress>\n"
            + "    <node-id>ROADM-B1</node-id>\n" + "    <current-defaultGateway>127.0.0.20</current-defaultGateway>\n"
            + "    <clli>NodeB</clli>\n" + "    <prefix-length>28</prefix-length>\n"
            + "    <current-prefix-length>28</current-prefix-length>\n"
            + "    <macAddress>00:01:02:03:04:05</macAddress>\n" + "    <source>static</source>\n"
            + "    <openroadm-version>2.2.1</openroadm-version>\n" + "    <geoLocation>\n"
            + "        <latitude>1.0000</latitude>\n" + "        <longitude>2.0000</longitude>\n"
            + "    </geoLocation>\n" + "    <max-num-bin-24hour-historical-pm>7</max-num-bin-24hour-historical-pm>\n"
            + "    <serial-id>0002</serial-id>\n" + "    <max-srgs>3</max-srgs>\n"
            + "    <max-num-bin-15min-historical-pm>32</max-num-bin-15min-historical-pm>\n"
            + "    <template>template_1</template>\n" + "    <node-type>rdm</node-type>\n"
            + "    <node-number>3</node-number>\n" + "    <ipAddress>127.0.0.11</ipAddress>\n"
            + "    <defaultGateway>127.0.0.20</defaultGateway>\n" + "</info>";
    private static final String NODEINFO = "{\"network-topology:node\":[{\"node-id\":\"roadmaa\","
            + "\"netconf-node-topology:unavailable-capabilities\":{\"unavailable-capability\":"
            + "[{\"capability\":\"(http://openconfig.net/yang/telemetry?revision=2017-08-24)openconfig-telemetry\","
            + "\"failure-reason\":\"unable-to-resolve\"},{\"capability\":\"(http://openconfig.net/yang/telemetry-types?"
            + "revision=2017-08-24)openconfig-telemetry-types\",\"failure-reason\":\"missing-source\"},"
            + "{\"capability\":\"(http://org/openroadm/telemetry-types?revision=2019-11-29)org-openroadm-telemetry-types\","
            + "\"failure-reason\":\"unable-to-resolve\"}]},\"netconf-node-topology:reconnect-on-changed-schema\":false,"
            + "\"netconf-node-topology:password\":\"undefind\",\"netconf-node-topology:username\":\"undefind\","
            + "\"netconf-node-topology:max-connection-attempts\":100,\"netconf-node-topology:tcp-only\":false,"
            + "\"netconf-node-topology:keepalive-delay\":120,\"netconf-node-topology:available-capabilities\":"
            + "{\"available-capability\":[{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"urn:ietf:params:netconf:capability:writable-running:1.0\"},{\"capability-origin\":"
            + "\"device-advertised\","
            + "\"capability\":\"urn:ietf:params:netconf:capability:notification:1.0\"},{\"capability-origin\":"
            + "\"device-advertised\",\"capability\":\"urn:ietf:params:netconf:base:1.0\"},{\"capability-origin\":"
            + "\"device-advertised\",\"capability\":\"(http://org/openroadm/common-state-types?revision=2019-11-29)"
            + "org-openroadm-common-state-types\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/common-attributes?revision=2019-11-29)org-openroadm-common-attributes\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/"
            + "media-channel-interfaces?"
            + "revision=2019-11-29)org-openroadm-media-channel-interfaces\"},{\"capability-origin\":"
            + "\"device-advertised\","
            + "\"capability\":\"(http://org/openroadm/common-equipment-types?revision=2019-11-29)"
            + "org-openroadm-common-"
            + "equipment-types\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/de/swdl?revision=2019-11-29)org-openroadm-swdl\"},{\"capability-origin\":"
            + "\"device-advertised\",\"capability\":\"(http://org/openroadm/key-chain?revision=2019-11-29)"
            + "org-openroadm-key-chain\"},{\"capability-origin\":\"device-advertised\",\"capability\":\"(urn:ietf:"
            + "params:xml:ns:yang:ietf-netconf-with-defaults?revision=2011-06-01)ietf-netconf-with-defaults\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/network-resource?"
            + "revision=2019-11-29)org-openroadm-network-resource\"},{\"capability-origin\":\"device-advertised\","
            + "\"capability\":\"(urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?revision=2012-02-06)"
            + "ietf-netconf-notifications\"},{\"capability\":\"(http://org/openroadm/otn-odu-interfaces?"
            + "revision=2019-11-29)org-openroadm-otn-odu-interfaces\"},{\"capability-origin\":\"device-advertised\","
            + "\"capability\":\"(http://org/openroadm/flexo-interfaces?revision=2019-11-29)org-"
            + "openroadm-flexo-interfaces\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/otn-common-"
            + "types?revision=2019-11-29)org-openroadm-otn-common-types\"},{\"capability-origin\":"
            + "\"device-advertised\"," + "\"capability\":\"(http://org/openroadm/service-format?revision=2019-11-29)"
            + "org-openroadm-service-format\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/resource?"
            + "revision=2019-11-29)"
            + "org-openroadm-resource\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(urn:ietf:params:xml:ns:yang:ietf-yang-types?revision=2013-07-15)ietf-yang-types\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://openconfig.net/yang/openconfig-ext?"
            + "revision=2017-04-11)openconfig-extensions\"},{\"capability-origin\":\"device-advertised\","
            + "\"capability\":\"(http://org/openroadm/device-types?revision=2019-11-29)org-openroadm-device-types\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/equipment/states/types?"
            + "revision=2019-11-29)org-openroadm-equipment-states-types\"},{\"capability-origin\":"
            + "\"device-advertised\","
            + "\"capability\":\"(http://org/openroadm/network-media-channel-interfaces?revision=2019-11-29)"
            + "org-openroadm-network-"
            + "media-channel-interfaces\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/"
            + "prot/otn-linear-aps?revision=2019-11-29)org-openroadm-prot-otn-linear-aps\"},{\"capability-origin\":"
            + "\"device-advertised\",\"capability\":\"(http://org/openroadm/common-node-types?revision=2019-11-29)"
            + "org-openroadm-common-node-types\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(urn:ietf:params:xml:ns:netconf:notification:1.0?revision=2008-07-14)notifications\"},"
            + "{\"capability-origin\":"
            + "\"device-advertised\",\"capability\":\"(http://org/openroadm/optical-channel-interfaces?revision=2019-11-29)"
            + "org-openroadm-optical-channel-interfaces\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/ip?revision=2019-11-29)org-openroadm-ip\"},{\"capability-origin\":"
            + "\"device-advertised\","
            + "\"capability\":\"(urn:ietf:params:xml:ns:yang:ietf-netconf-acm?revision=2018-02-14)ietf-netconf-acm\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/fwdl?revision=2019-11-29)"
            + "org-openroadm-fwdl\"},{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://"
            + "org/openroadm/physical/types?revision=2019-11-29)org-openroadm-physical-types\"},{\"capability-origin\":"
            + "\"device-advertised\",\"capability\":\"(http://org/openroadm/manifest-file?revision=2019-11-29)org-"
            + "openroadm-manifest-file\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://openconfig.net/yang/types/inet?revision=2017-08-24)openconfig-inet-types\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(urn:ietf:params:"
            + "xml:ns:yang:iana-crypt-hash?"
            + "revision=2014-08-06)iana-crypt-hash\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/dhcp?revision=2019-11-29)org-openroadm-dhcp\"},{\"capability-origin\":"
            + "\"device-advertised\",\"capability\":\"(http://org/openroadm/database?revision=2019-11-29)"
            + "org-openroadm-database\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/optical-operational-interfaces?revision=2019-11-29)org-openroadm-optical-"
            + "operational-interfaces\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/de/operations?revision=2019-11-29)org-openroadm-de-operations\"},"
            + "{\"capability\":\"(http://org/openroadm/ethernet-interfaces?revision=2019-11-29)"
            + "org-openroadm-ethernet-interfaces\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/syslog?revision=2019-11-29)"
            + "org-openroadm-syslog\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/optical-"
            + "transport-interfaces?revision=2019-11-29)org-openroadm-optical-transport-interfaces\"},"
            + "{\"capability-origin\":"
            + "\"device-advertised\",\"capability\":\"(http://org/openroadm/user-mgmt?revision=2019-11-29)"
            + "org-openroadm-user-mgmt\"},"
            + "{\"capability\":\"(http://org/openroadm/gnmi?revision=2019-11-29)org-openroadm-gnmi\"},{\"capability-origin\":"
            + "\"device-advertised\",\"capability\":\"(http://org/openroadm/layerRate?revision=2019-11-29)org-openroadm-layerRate\"}"
            + ",{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/probableCause?"
            + "revision=2019-11-29)org-openroadm-probable-cause\"},{\"capability-origin\":\"device-advertised\","
            + "\"capability\":\"(http://org/openroadm/common-link-types?revision=2019-11-29)"
            + "org-openroadm-common-link-types\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(urn:ietf:params:xml:ns:"
            + "netmod:notification?"
            + "revision=2008-07-14)nc-notifications\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/optical-channel-tributary-signal-interfaces?revision=2019-11-29)org-openroadm-optical-"
            + "tributary-signal-interfaces\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/otn-common?revision=2019-11-29)org-openroadm-otn-common\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(urn:ietf:params:xml:ns:netconf:base:1.0?"
            + "revision=2011-06-01)ietf-netconf\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/port/types?revision=2019-11-29)org-openroadm-port-types\"},{\"capability-origin\":"
            + "\"device-advertised\",\"capability\":\"(http://org/openroadm/file-transfer?revision=2019-11-29)"
            + "org-openroadm-file-transfer\"},{\"capability\":\"(http://org/openroadm/maintenance-testsignal?"
            + "revision=2019-11-29)org-openroadm-maintenance-testsignal\"},{\"capability-origin\":"
            + "\"device-advertised\","
            + "\"capability\":\"(http://org/openroadm/alarm?revision=2019-11-29)org-openroadm-alarm\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(urn:ietf:params:xml:ns:"
            + "yang:ietf-inet-types?"
            + "revision=2013-07-15)ietf-inet-types\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/otsigroup-capability?revision=2019-11-29)org-openroadm-otsigroup-capability\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/ppp-interfaces?revision="
            + "2019-11-29)org-openroadm-ppp-interfaces\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/common-amplifier-types?revision=2019-11-29)org-openroadm-common-amplifier-types\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/resource/types?revision="
            + "2019-11-29)org-openroadm-resource-types\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/device?revision=2019-11-29)org-openroadm-device\"},{\"capability-origin\":"
            + "\"device-advertised\",\"capability\":\"(http://org/openroadm/port-capability?revision=2019-11-29)"
            + "org-openroadm-port-capability\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/maintenance-loopback?revision=2019-11-29)org-openroadm-maintenance-loopback\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/pm-types?"
            + "revision=2019-11-29)org-openroadm-pm-types\"},{\"capability\":\"(http://org/openroadm/security?"
            + "revision=2019-11-29)org-openroadm-security\"},{\"capability-origin\":\"device-advertised\","
            + "\"capability\":"
            + "\"(urn:ietf:params:xml:ns:yang:ietf-system?revision=2014-08-06)ietf-system\"},{\"capability-origin\":"
            + "\"device-advertised\",\"capability\":\"(http://org/openroadm/wavelength-map?revision=2019-11-29)"
            + "org-openroadm-wavelength-map\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/otsi-group-interfaces?revision=2019-11-29)org-openroadm-otsi-group-interfaces\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/tca?revision=2019-11-29)"
            + "org-openroadm-tca\"},{\"capability-origin\":\"device-advertised\",\"capability\":"
            + "\"(http://org/openroadm/common-optical-channel-types?revision=2019-11-29)org-openroadm-common-"
            + "optical-channel-types\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/flexogroup-interfaces?"
            + "revision=2019-11-29)org-openroadm-flexogroup-interfaces\"},{\"capability-origin\":\"device-advertised\","
            + "\"capability\":\"(http://org/openroadm/interfaces?revision=2019-11-29)org-openroadm-interfaces\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/otn-otu-interfaces?"
            + "revision=2019-11-29)org-openroadm-otn-otu-interfaces\"},{\"capability-origin\":\"device-advertised\","
            + "\"capability\":\"(http://org/openroadm/common-types?revision=2019-11-29)org-openroadm-common-types\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/gcc-interfaces?"
            + "revision=2019-11-29)org-openroadm-gcc-interfaces\"},{\"capability-origin\":\"device-advertised\","
            + "\"capability\":\"(urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?revision=2010-10-04)ietf"
            + "-netconf-monitoring\"},"
            + "{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/switching-pool-types?"
            + "revision=2019-11-29)org-openroadm-switching-pool-types\"},{\"capability-origin\":\"device-advertised\","
            + "\"capability\":\"(http://org/openroadm/common-alarm-pm-types?revision=2019-11-29)org-openroadm-common"
            + "-alarm-pm-types\"},{\"capability-origin\":\"device-advertised\",\"capability\":\"(http://org/openroadm/"
            + "rstp?revision=2019-11-29)org-openroadm-rstp\"},{\"capability-origin\":\"device-advertised\","
            + "\"capability\":"
            + "\"(http://org/openroadm/pm?revision=2019-11-29)org-openroadm-pm\"}]},\"netconf-node-topology:sleep"
            + "-factor\":"
            + "1.5,\"netconf-node-topology:connection-timeout-millis\":20000,\"netconf-node-topology:port\":4000,"
            + "\"netconf-node-topology:host\":\"192.168.178.169\",\"netconf-node-topology:between-attempts-timeout"
            + "-millis\":" + "2000,\"netconf-node-topology:connection-status\":\"connected\"}]}";
    private static final String NODEINFO_XML = "<node xmlns=\"urn:TBD:params:xml:ns:yang:network-topology\">\n"
            + "    <node-id>roadmaa</node-id>\n"
            + "    <unavailable-capabilities xmlns=\"urn:opendaylight:netconf-node-topology\">\n"
            + "        <unavailable-capability>\n"
            + "            <capability>(http://openconfig.net/yang/telemetry?revision=2017-08-24)"
            + "openconfig-telemetry</capability>\n" + "            <failure-reason>unable-to-resolve</failure-reason>\n"
            + "        </unavailable-capability>\n" + "        <unavailable-capability>\n"
            + "            <capability>(http://openconfig.net/yang/telemetry-types?"
            + "revision=2017-08-24)openconfig-telemetry-types</capability>\n"
            + "            <failure-reason>missing-source</failure-reason>\n" + "        </unavailable-capability>\n"
            + "        <unavailable-capability>\n"
            + "            <capability>(http://org/openroadm/telemetry-types?revision=2019-11-29)"
            + "org-openroadm-telemetry-types</capability>\n"
            + "            <failure-reason>unable-to-resolve</failure-reason>\n" + "        </unavailable-capability>\n"
            + "    </unavailable-capabilities>\n"
            + "    <reconnect-on-changed-schema xmlns=\"urn:opendaylight:netconf-node-topology\">"
            + "false</reconnect-on-changed-schema>\n"
            + "    <password xmlns=\"urn:opendaylight:netconf-node-topology\">undefind</password>\n"
            + "    <username xmlns=\"urn:opendaylight:netconf-node-topology\">undefind</username>\n"
            + "    <max-connection-attempts xmlns=\"urn:opendaylight:netconf-node-topology\">"
            + "100</max-connection-attempts>\n"
            + "    <tcp-only xmlns=\"urn:opendaylight:netconf-node-topology\">false</tcp-only>\n"
            + "    <keepalive-delay xmlns=\"urn:opendaylight:netconf-node-topology\">120</keepalive-delay>\n"
            + "    <available-capabilities xmlns=\"urn:opendaylight:netconf-node-topology\">\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>urn:ietf:params:netconf:base:1.0</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/common-state-types?"
            + "revision=2019-11-29)org-openroadm-common-state-types</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/common-attributes?"
            + "revision=2019-11-29)org-openroadm-common-attributes</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/media-channel-interfaces?"
            + "revision=2019-11-29)org-openroadm-media-channel-interfaces</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/common-equipment-types?"
            + "revision=2019-11-29)org-openroadm-common-equipment-types</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/de/swdl?revision=2019-11-29)"
            + "org-openroadm-swdl</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/key-chain?revision=2019-11-29)"
            + "org-openroadm-key-chain</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?"
            + "revision=2011-06-01)ietf-netconf-with-defaults</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/network-resource?revision=2019-11-29)"
            + "org-openroadm-network-resource</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?"
            + "revision=2012-02-06)ietf-netconf-notifications</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability>(http://org/openroadm/otn-odu-interfaces?revision=2019-11-29)"
            + "org-openroadm-otn-odu-interfaces</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/flexo-interfaces?revision=2019-11-29)"
            + "org-openroadm-flexo-interfaces</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/otn-common-types?revision=2019-11-29)"
            + "org-openroadm-otn-common-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/service-format?revision=2019-11-29)"
            + "org-openroadm-service-format</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/resource?revision=2019-11-29)"
            + "org-openroadm-resource</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(urn:ietf:params:xml:ns:yang:ietf-yang-types?"
            + "revision=2013-07-15)ietf-yang-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://openconfig.net/yang/openconfig-ext?"
            + "revision=2017-04-11)openconfig-extensions</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/device-types?revision=2019-11-29)"
            + "org-openroadm-device-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/equipment/states/types?"
            + "revision=2019-11-29)org-openroadm-equipment-states-types</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/network-media-channel-interfaces?"
            + "revision=2019-11-29)org-openroadm-network-media-channel-interfaces</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/prot/otn-linear-aps?"
            + "revision=2019-11-29)org-openroadm-prot-otn-linear-aps</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/common-node-types?"
            + "revision=2019-11-29)org-openroadm-common-node-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(urn:ietf:params:xml:ns:netconf:notification:1.0?"
            + "revision=2008-07-14)notifications</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/optical-channel-interfaces?"
            + "revision=2019-11-29)org-openroadm-optical-channel-interfaces</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/ip?revision=2019-11-29)"
            + "org-openroadm-ip</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(urn:ietf:params:xml:ns:yang:ietf-netconf-acm?"
            + "revision=2018-02-14)ietf-netconf-acm</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/fwdl?revision=2019-11-29)"
            + "org-openroadm-fwdl</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/physical/types?revision=2019-11-29)"
            + "org-openroadm-physical-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/manifest-file?revision=2019-11-29)"
            + "org-openroadm-manifest-file</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://openconfig.net/yang/types/inet?"
            + "revision=2017-08-24)openconfig-inet-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(urn:ietf:params:xml:ns:yang:iana-crypt-hash?"
            + "revision=2014-08-06)iana-crypt-hash</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/dhcp?revision=2019-11-29)"
            + "org-openroadm-dhcp</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/database?revision=2019-11-29)"
            + "org-openroadm-database</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/optical-operational-interfaces?"
            + "revision=2019-11-29)org-openroadm-optical-operational-interfaces</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/de/operations?"
            + "revision=2019-11-29)org-openroadm-de-operations</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n" + "            <capability>(http://org/openroadm/ethernet-interfaces?"
            + "revision=2019-11-29)org-openroadm-ethernet-interfaces</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/syslog?revision=2019-11-29)"
            + "org-openroadm-syslog</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/optical-transport-interfaces?"
            + "revision=2019-11-29)org-openroadm-optical-transport-interfaces</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/user-mgmt?revision=2019-11-29)"
            + "org-openroadm-user-mgmt</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability>(http://org/openroadm/gnmi?revision=2019-11-29)"
            + "org-openroadm-gnmi</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/layerRate?"
            + "revision=2019-11-29)org-openroadm-layerRate</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/probableCause?"
            + "revision=2019-11-29)org-openroadm-probable-cause</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/common-link-types?"
            + "revision=2019-11-29)org-openroadm-common-link-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(urn:ietf:params:xml:ns:netmod:notification?"
            + "revision=2008-07-14)nc-notifications</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/optical-channel-tributary-signal-interfaces?"
            + "revision=2019-11-29)org-openroadm-optical-tributary-signal-interfaces</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/otn-common?revision=2019-11-29)"
            + "org-openroadm-otn-common</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(urn:ietf:params:xml:ns:netconf:base:1.0?"
            + "revision=2011-06-01)ietf-netconf</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/port/types?revision=2019-11-29)"
            + "org-openroadm-port-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/file-transfer?revision=2019-11-29)"
            + "org-openroadm-file-transfer</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability>(http://org/openroadm/maintenance-testsignal?"
            + "revision=2019-11-29)org-openroadm-maintenance-testsignal</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/alarm?revision=2019-11-29)"
            + "org-openroadm-alarm</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(urn:ietf:params:xml:ns:yang:ietf-inet-types?"
            + "revision=2013-07-15)ietf-inet-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/otsigroup-capability?"
            + "revision=2019-11-29)org-openroadm-otsigroup-capability</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/ppp-interfaces?revision=2019-11-29)"
            + "org-openroadm-ppp-interfaces</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/common-amplifier-types?"
            + "revision=2019-11-29)org-openroadm-common-amplifier-types</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/resource/types?revision=2019-11-29)"
            + "org-openroadm-resource-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/device?revision=2019-11-29)"
            + "org-openroadm-device</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/port-capability?revision=2019-11-29)"
            + "org-openroadm-port-capability</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/maintenance-loopback?revision=2019-11-29)"
            + "org-openroadm-maintenance-loopback</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/pm-types?revision=2019-11-29)"
            + "org-openroadm-pm-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability>(http://org/openroadm/security?revision=2019-11-29)"
            + "org-openroadm-security</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(urn:ietf:params:xml:ns:yang:ietf-system?"
            + "revision=2014-08-06)ietf-system</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/wavelength-map?revision=2019-11-29)"
            + "org-openroadm-wavelength-map</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/otsi-group-interfaces?revision=2019-11-29)"
            + "org-openroadm-otsi-group-interfaces</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/tca?revision=2019-11-29)org-openroadm-tca</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/common-optical-channel-types?revision=2019-11-29)"
            + "org-openroadm-common-optical-channel-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/flexogroup-interfaces?revision=2019-11-29)"
            + "org-openroadm-flexogroup-interfaces</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/interfaces?revision=2019-11-29)"
            + "org-openroadm-interfaces</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/otn-otu-interfaces?revision=2019-11-29)"
            + "org-openroadm-otn-otu-interfaces</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/common-types?revision=2019-11-29)"
            + "org-openroadm-common-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/gcc-interfaces?revision=2019-11-29)"
            + "org-openroadm-gcc-interfaces</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?"
            + "revision=2010-10-04)ietf-netconf-monitoring</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/switching-pool-types?revision=2019-11-29)"
            + "org-openroadm-switching-pool-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/common-alarm-pm-types?revision=2019-11-29)"
            + "org-openroadm-common-alarm-pm-types</capability>\n" + "        </available-capability>\n"
            + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/rstp?revision=2019-11-29)org-openroadm-rstp</capability>\n"
            + "        </available-capability>\n" + "        <available-capability>\n"
            + "            <capability-origin>device-advertised</capability-origin>\n"
            + "            <capability>(http://org/openroadm/pm?revision=2019-11-29)org-openroadm-pm</capability>\n"
            + "        </available-capability>\n" + "    </available-capabilities>\n"
            + "    <sleep-factor xmlns=\"urn:opendaylight:netconf-node-topology\">1.5</sleep-factor>\n"
            + "    <connection-timeout-millis xmlns=\"urn:opendaylight:netconf-node-topology\">"
            + "20000</connection-timeout-millis>\n"
            + "    <port xmlns=\"urn:opendaylight:netconf-node-topology\">4000</port>\n"
            + "    <host xmlns=\"urn:opendaylight:netconf-node-topology\">192.168.178.169</host>\n"
            + "    <between-attempts-timeout-millis xmlns=\"urn:opendaylight:netconf-node-topology\">"
            + "2000</between-attempts-timeout-millis>\n"
            + "    <connection-status xmlns=\"urn:opendaylight:netconf-node-topology\">connected</connection-status>\n"
            + "</node>";

    // @Test
    public void testMapRoadmInfo()
            throws ClassNotFoundException, JsonParseException, JsonMappingException, IOException {
        OdlObjectMapper jsonMapper = new OdlObjectMapper();
        OdlObjectMapperXml xmlMapper = new OdlObjectMapperXml();
        LOG.info("outputjson={}", jsonMapper.readValue(INFOSTRING, Info.class, "org-openroadm-device:info"));
        LOG.info("outputxml={}", xmlMapper.readValue(INFOSTRING_XML, Info.class));
    }

    // @Test
    public void testNodeInfo() throws JsonParseException, JsonMappingException, IOException {
        OdlObjectMapper jsonMapper = new OdlObjectMapper();
        OdlObjectMapperXml xmlMapper = new OdlObjectMapperXml();
        LOG.info("outputjson={}", jsonMapper.readValue(NODEINFO, NetconfNode.class, "network-topology:node"));
        LOG.info("outputxml={}", xmlMapper.readValue(NODEINFO_XML, NetconfNode.class));

    }

    private static SchemaContext SCHEMA_CONTEXT;

    @BeforeClass
    public static void beforeClass() {
        // SCHEMA_CONTEXT = YangParserTestUtils.parseYangResourceDirectory("/yang");
        try {
            SCHEMA_CONTEXT = YangParserTestUtils.parseYangResources("/yang/ietf-yang-types@2013-07-15.yang",
                    "/yang/ietf-inet-types@2013-07-15.yang", "/yang/ietf-netconf-acm@2018-02-14.yang",
                    "/yang/ietf-netconf@2011-06-01.yang",

                    "/yang/org-openroadm-common-types@2019-11-29.yang",
                    "/yang/org-openroadm-common-alarm-pm-types@2019-11-29.yang",
                    "/yang/org-openroadm-common-equipment-types@2019-11-29.yang",
                    "/yang/org-openroadm-common-state-types@2019-11-29.yang",
                    "/yang/org-openroadm-common-amplifier-types@2019-11-29.yang",
                    "/yang/org-openroadm-common-link-types@2019-11-29.yang",
                    "/yang/org-openroadm-common-node-types@2019-11-29.yang",
                    "/yang/org-openroadm-common-optical-channel-types@2019-11-29.yang",
                    "/yang/org-openroadm-device-types@2019-11-29.yang",
                    "/yang/org-openroadm-resource-types@2019-11-29.yang",
                    "/yang/org-openroadm-physical-types@2019-11-29.yang",
                    "/yang/org-openroadm-user-mgmt@2019-11-29.yang", "/yang/org-openroadm-port-types@2019-11-29.yang",
                    "/yang/org-openroadm-interfaces@2019-11-29.yang", "/yang/org-openroadm-swdl@2019-11-29.yang",
                    "/yang/org-openroadm-equipment-states-types@2019-11-29.yang",
                    "/yang/org-openroadm-switching-pool-types@2019-11-29.yang",
                    "/yang/org-openroadm-device@2019-11-29.yang");
            LOG.info("schema read succeeded");
        } catch (Exception e) {
            LOG.error("unable to read all schemas: ", e);
        }
    }

    @AfterClass
    public static void afterClass() {
        SCHEMA_CONTEXT = null;
    }

    @Test
    public void testRpcSerializer() throws JsonProcessingException, XMLStreamException, ParserConfigurationException, TransformerException {
        final String LEDRPCINPUT = "<input><enabled>true</enabled><shelf-name>1/0</shelf-name></input>";
        if (SCHEMA_CONTEXT == null) {
            fail();
        }
        OdlRpcObjectMapperXml2 mapper = new OdlRpcObjectMapperXml2();

        final LedControlInputBuilder builder = new LedControlInputBuilder();
        builder.setEnabled(true).setEquipmentEntity(new ShelfBuilder().setShelfName("1/0").build());
        String inputPayload = mapper.writeValueAsString(builder.build());
        try {
            XMLUnit.compareXML(LEDRPCINPUT, inputPayload);
        } catch (SAXException | IOException e) {
            fail(e.getMessage());
        }
    }

    @Test
    public void testLeafListSerializing() {

    }
}
