version: '3'

services:
  transportpce:
    image: odl/transportpce
    volumes: 
      - ./conf/remoteodl.properties:/opt/opendaylight/etc/remoteodl.properties
    environment: 
      - REMOTE_SDNRURL=http://sdnr:8181
      - REMOTE_WSURL=ws://sdnr:8181/websocket
      - REMOTE_ODL_USERNAME=${SDNR_USERNAME}
      - REMOTE_ODL_PASSWORD=${SDNR_PASSWORD}
      - REMOTE_ODL_ENABLED=${REMOTE_ODL_ENABLED}
      - REMOTE_ODL_TRUSTALL=${TRUSTALL}
    depends_on: 
      - sdnr
  sdncweb:
    image: nexus3.onap.org:10001/onap/sdnc-web-image:latest
    environment: 
      - SDNRHOST=sdnr
    depends_on: 
      - sdnr
  sdnr:
#    image: nexus3.onap.org:10001/onap/sdnc-image:1.8.4-STAGING-latest
    image: hightec/sdnr-image-sodium:1.0.0-SNAPSHOT-20200720T171600Z
    environment: 
      - SDNRONLY=true
      - SDNRINIT=true
      - SDNRDM=true
      - SDNRWT=true
      - SDNRDBURL=http://sdnrdb:9200
#    entrypoint: /opt/onap/sdnc/bin/startODL.oom.sh
    depends_on: 
      - sdnrdb
  sdnrdb:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.4
    environment: 
      - discovery.type=single-node
  roadma:
    image: netconfserversimulator
    environment: 
      - XMLFILE=xmlNeModel/openroadm-A.xml
      - PORT=4000
    depends_on: 
      - sdnr
  roadmb:
    image: netconfserversimulator
    environment: 
      - XMLFILE=xmlNeModel/openroadm-B.xml
      - PORT=4000
    depends_on: 
      - sdnr
  roadmc:
    image: netconfserversimulator
    environment: 
      - XMLFILE=xmlNeModel/openroadm-C.xml
      - PORT=4000
    depends_on: 
      - sdnr  
  xpdra:
    image: netconfserversimulator
    environment: 
      - XMLFILE=xmlNeModel/openroadm-XPDR-A.xml
      - PORT=4000
    depends_on: 
      - sdnr      
  xpdrc:
    image: netconfserversimulator
    environment: 
      - XMLFILE=xmlNeModel/openroadm-XPDR-C.xml
      - PORT=4000
    depends_on: 
      - sdnr
                                          
