server:
  port: 8082

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
onap:
  aaf:
    url: https://aaf.api.simpledemo.onap.org:31369/locate/AAF_NS.service:2.1
    user_fqi: aaf@aaf.osaaf.org
    user_pass: demo123456!
    aaf_id: mmanager@people.osaaf.org
    aaf_password: demo123456!

  api:
    username: admin
    password: admin
    network-url-path: http://transportpce:8181/restconf/config/ietf-network:networks
    #network-url-path: http://localhost:3000/restconf/config/ietf-network:networks
    service-path-list: http://transportpce:8181/restconf/operational/transportpce-servicepath:service-path-list
    service-url-path: http://transportpce:8181/restconf/operational/org-openroadm-service:service-list
    #service-url-path: http://localhost:3000/restconf/config/org-openroadm-service:service-list
---
spring:
  profiles: int
onap:
  aaf:
    url: https://aaf.api.simpledemo.onap.org:31369/locate/AAF_NS.service:2.1
    user_fqi: aaf@aaf.osaaf.org
    user_pass: demo123456!
    aaf_id: mmanager@people.osaaf.org
    aaf_password: demo123456!
