version: '3'

services:
  transportpce:
    image: odl/transportpce
    volumes: 
      - ./conf/remoteodl.properties:/opt/opendaylight/etc/remoteodl.properties
    environment: 
      - REMOTE_SDNRURL=http://sdnr:8181
      - REMOTE_WSURL=ws://sdnr:8181/websocket
      - REMOTE_ODL_USERNAME=${SDNR_USERNAME}
      - REMOTE_ODL_PASSWORD=${SDNR_PASSWORD}
      - REMOTE_ODL_ENABLED=${REMOTE_ODL_ENABLED}
      - REMOTE_ODL_TRUSTALL=${TRUSTALL}
    depends_on: 
      - sdnr
  sdncweb:
#    image: nexus3.onap.org:10001/onap/sdnc-web-image:latest
    image: 10.20.6.10:30000/hightec/sdnc-web-image:2.0.0-SNAPSHOT-20200731T064656Z
    environment: 
      - SDNRHOST=sdnr
    depends_on: 
      - sdnr
  sdnr:
#    image: nexus3.onap.org:10001/onap/sdnc-image:1.8.4-STAGING-latest
    image: hightec/sdnr-image-sodium:1.0.0-SNAPSHOT-20200720T171600Z
    environment: 
      - SDNRONLY=true
      - SDNRINIT=true
      - SDNRDM=true
      - SDNRWT=true
      - SDNRDBURL=http://sdnrdb:9200
      - SDNRWT_BOOTFEATURES=odl-netconf-callhome-ssh,sdnr-wt-feature-aggregator
#    entrypoint: /opt/onap/sdnc/bin/startODL.oom.sh
    depends_on: 
      - sdnrdb
  sdnrdb:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.4
    environment: 
      - discovery.type=single-node
  roadma:
    image: ${NTSIM_ROADM_STANDALONE_IMAGE}
    environment: 
      - NTS_IP=10.20.11.121
      - EXTERNAL_NTS_IP=10.20.11.121
      - NETCONF_BASE=${SIMPORT}
      - SCRIPTS_DIR=/opt/dev/scripts
      - K8S_DEPLOYMENT=false
      - IPv6Enabled=false
    volumes: 
      - ./conf/ntsim_configuration.json:/opt/dev/scripts/configuration.json
      - ./conf/oper-ROADMA.xml:/opt/dev/scripts/startup-load.xml
    depends_on: 
      - sdnr
  roadmb:
    image: ${NTSIM_ROADM_STANDALONE_IMAGE}
    environment: 
      - NTS_IP=10.20.11.121
      - EXTERNAL_NTS_IP=10.20.11.121
      - NETCONF_BASE=${SIMPORT}
      - SCRIPTS_DIR=/opt/dev/scripts
      - K8S_DEPLOYMENT=false
      - IPv6Enabled=false
    volumes: 
      - ./conf/ntsim_configuration.json:/opt/dev/scripts/configuration.json
      - ./conf/oper-ROADMB.xml:/opt/dev/scripts/startup-load.xml
    depends_on: 
      - sdnr
  roadmc:
    image: ${NTSIM_ROADM_STANDALONE_IMAGE}
    environment: 
      - NTS_IP=10.20.11.121
      - EXTERNAL_NTS_IP=10.20.11.121
      - NETCONF_BASE=${SIMPORT}
      - SCRIPTS_DIR=/opt/dev/scripts
      - K8S_DEPLOYMENT=false
      - IPv6Enabled=false
    volumes: 
      - ./conf/ntsim_configuration.json:/opt/dev/scripts/configuration.json
      - ./conf/oper-ROADMC.xml:/opt/dev/scripts/startup-load.xml
    depends_on: 
      - sdnr  
  xpdra:
    image: ${NTSIM_ROADM_STANDALONE_IMAGE}
    environment: 
      - NTS_IP=10.20.11.121
      - EXTERNAL_NTS_IP=10.20.11.121
      - NETCONF_BASE=${SIMPORT}
      - SCRIPTS_DIR=/opt/dev/scripts
      - K8S_DEPLOYMENT=false
      - IPv6Enabled=false
    volumes: 
      - ./conf/ntsim_configuration.json:/opt/dev/scripts/configuration.json
      - ./conf/oper-XPDRA.xml:/opt/dev/scripts/startup-load.xml
    depends_on: 
      - sdnr      
  xpdrc:
    image: ${NTSIM_ROADM_STANDALONE_IMAGE}
    environment: 
      - NTS_IP=10.20.11.121
      - EXTERNAL_NTS_IP=10.20.11.121
      - NETCONF_BASE=${SIMPORT}
      - SCRIPTS_DIR=/opt/dev/scripts
      - K8S_DEPLOYMENT=false
      - IPv6Enabled=false
    volumes: 
      - ./conf/ntsim_configuration.json:/opt/dev/scripts/configuration.json
      - ./conf/oper-XPDRC.xml:/opt/dev/scripts/startup-load.xml
    depends_on: 
      - sdnr
                                          
